public With sharing class SharingRulesApex {
    
    public static void enforceSharingRules(List<Account> lstAccounts) 
    {
        String strCount = InheritedSharingDemo.updateAccountAccessibleCount();
        system.debug('Accessible Accounts Count: ' + strCount);
        for(Account acc : lstAccounts)
        {
            //check field level permission of Accounts Active__c field
            acc.Description = strCount;


            //check field level update permission of the Accounts Active field before updating it
           // if(Schema.SObjectType.Account.fields.Active__c.isUpdateable()) //isCraeateable,isAccessible
                acc.Active__c = 'Yes';
            
          
            //Check object level permission for the Account object before deleting
            /*if(Schema.SObjectType.Account.isDeletable())
            {

            }*/
        }
    }
}